name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android_app/gradlew

      - name: Build with Gradle
        working-directory: ./android_app
        run: ./gradlew assembleDebug

      - name: Build Release APK
        working-directory: ./android_app
        run: ./gradlew assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: geoimage-app-debug
          path: android_app/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: geoimage-app-release-unsigned
          path: android_app/app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            android_app/app/build/outputs/apk/debug/app-debug.apk
            android_app/app/build/outputs/apk/release/app-release-unsigned.apk